### ISSUE TITLE
Text generator

### ISSUE THREAD

**Issue by ChrisTerBeke** [PRINTR3D/javascript-3d-doodler#3]
Option to add text to the 2D canvas and then render to 3D

**Comment by FlorisVeldhuizen** [comment]
4h in, already some good functionality. Having trouble with the save state, I think I'm gonna rewrite the whole canvas history.

**Comment by FlorisVeldhuizen** [comment]
add 4h, almost done with correcting history. still a pesky bug :\

**Comment by ChrisTerBeke** [comment]
screenshots?! :P

**Comment by FlorisVeldhuizen** [comment]
woohoooo! add 2h and the history function now works (push pop magic!), along with extra functionality of the cursor! let's get this text function finished baby! :)

**Comment by FlorisVeldhuizen** [comment]
alright, 2h extra and text finally works (with angular too!). next up: change font size! this won't take too long.
